version: '3.7'

services:
    backend_2:
        build: ./API_2/simple-api-student-main
        container_name: my-java-api-2
        ports:
        - 8080:8080
        depends_on:
        - db
    backend_1:
        build: ./API_2/simple-api-student-main
        container_name: my-java-api-1
        ports:
        - 8082:8080
        depends_on:
        - db
    db:
        container_name: bdd_pg
        build: ./BDD
        ports:
        - 5432:5432
        environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pwd
        volumes:
        - /my/own/datadir:/var/lib/postgresql/data
    httpd:
        container_name: http_front
        build: ./HTTP
        ports:
        - 82:80
        depends_on:
        - backend_1
        - backend_2
    httpd-2:
        build: ./FRONT/devops-front
        ports:
        - 80:80
        depends_on:
        - httpd
    graphana:
        build: ./GRAPH/grafana-main
        depends_on:
        - httpd

networks:
    app-network:
      driver: bridge